name: Build docker image
on: ['push','pull_request']
    
jobs:
# TODO: Move all this functionality into a Makefile and get it to use the docker container so everything can be done locally.
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Cache NPM deps
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-modules-
      
      - name: Install dependencies
        run: npm install
      
      - name: run linters
        run: npm run lint
      
      - name: Run unit tests
        run: npm run test:unit
      
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.sha }}

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os}}-node-modules-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      
      - name: Install dependencies
        run: |
          npm install

      - name: Build Frontend Artifact
        env:
          VUE_APP_API_URL: ${{ github.event.inputs.backendUrl }}
        run: |
          yarn run build

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: todo-frontend-${{ github.sha }}
          path: dist/
          retention-days: 5

  docker-build-latest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Export variables
        id: vars
        run: |
          echo "::set-output name=branch_name::$(echo ${GITHUB_REF} | cut -d '/' -f 3 )"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os}}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - uses: actions/download-artifact@v2
        with:
          name: todo-frontend-${{ github.sha }}
          path: dist/

      - name: Build and push 
        uses: docker/build-push-action@v2
        if: ${{ ! startsWith(github.ref, 'refs/tags/v') }}
        with:
          context: .
          push: true
          pull: true
          tags: joelfreeman/todo-backend:${{ steps.vars.outputs.branch_name }}_${{ steps.vars.outputs.sha_short }}, joelfreeman/todo-frontend:latest
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline

      - name: Build and push (tag)
        uses: docker/build-push-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        with:
          context: .
          push: true
          pull: true
          tags: joelfreeman/todo-backend:${{ steps.vars.outputs.sha_short }}, jfreemxn/todo-frontend:${{ env.GIT_TAG_NAME }}, joelfreeman/todo-frontend:latest
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline
      
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/joelfreeman/todo-frontend:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'