
name: Deploy site to S3
on:
  workflow_run:
    workflows: ["Build docker image and run tests"]
    branches: ['main']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: joelfreeman/todo-frontend:latest
      # This isn't ideal as we're forced to choose the latest tag - instead of specifying one directly. But it works!
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-skip-session-tagging: true
          role-duration-seconds: 1200
          aws-region: us-east-1
      - name: Deploy to S3
        run: /usr/local/bin/deploy.sh
